Novo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from usuario import urls as urlsUsuario
from usuario.views import Index
from materia import urls as urlsMateria
from semestre import urls as urlsSemestre
from tarea import urls as urlsTarea
from examen import urls as urlsExamen
from usuario.api import urls as materiasAPI
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Index.as_view(), name='index'),
    url(r'^usuario/', include(urlsUsuario, namespace='usuario')),
    url(r'^materia/', include(urlsMateria, namespace='materia')),
    url(r'^tarea/', include(urlsTarea, namespace='tarea')),
    url(r'^examen/', include(urlsExamen, namespace='examen')),
    url(r'^semestre/', include(urlsSemestre, namespace='semestre')),
    url(r'^apiv1/', include(materiasAPI, namespace='apiv1')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materia/urls.py
from django.conf.urls import url
from .views import Materia, Detalles

urlpatterns = [
    url(r'^horario', Materia.as_view(), name='materia'),
    url(r'^detalle/(?P<pk>[0-9]+)/$', Detalles.as_view(), name='editar')
    # url(r'^materias/', Horario.as_view(), name='materias'),
]

materia/models.py
from django.db import models
from django.contrib.auth.models import User
from semestre.models import semestre


class datoshorario(models.Model):
    user = models.OneToOneField(User, blank=True, null=True)
    semestre = models.ForeignKey(
        semestre, blank=False, null=False, related_name='semestres'
        )


class datosmateria(models.Model):
    materia = models.CharField(blank=False, null=False, max_length=50)
    profesor = models.CharField(blank=False, null=False, max_length=60)
    horario = models.ForeignKey(
        datoshorario, blank=False, null=False, related_name='horarios'
        )
    grupo = models.CharField(blank=True, null=True, max_length=6)

    def __str__(self):
        return '{}'.format(self.materia)


class horas(models.Model):
    hora = models.CharField(blank=True, null=True, max_length=30)
    fin = models.CharField(blank=True, null=True, max_length=30)
    fecha = models.CharField(blank=True, null=True, max_length=30)
    materia = models.ForeignKey(
        datosmateria, blank=False, null=False, related_name='materias'
        )


class semana(models.Model):
    dia = models.CharField(blank=False, null=False, max_length=10)
    horai = models.CharField(blank=True, null=False, max_length=6)
    horaf = models.CharField(blank=True, null=False, max_length=6)
    materia = models.ForeignKey(datosmateria, blank=False, null=False)

materia/forms.py
from django import forms
from .models import *
from django.utils.translation import ugettext_lazy as _


class MateriaForm(forms.ModelForm):
    class Meta:
        model = datosmateria
        fields = ('materia', 'profesor', 'grupo')
        labels = {
            'materia': _(''),
            'profesor': _(''),
            'grupo': _('')
        }
        widgets = {
            'materia': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nombre de la materia',
                    'required': 'true'
                }
            ),
            'profesor': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Profesor que imparte',
                    'required': 'true'
                }
            ),
            'grupo': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Grupo de la materia',
                    'required': 'true'
                }
            ),
        }

materia/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from .forms import MateriaForm
from .registers import guardar_materia, eliminar_materias, cambiar_materia
from .models import *
from django.http import HttpResponseRedirect
from utils.registers import cambiar_hora, eliminar_hora


class Materia(View):
    def get(self, request):
        template_name = 'materias.html'
        materia = MateriaForm()
        try:
            horario = datoshorario.objects.get(user=request.user)
            materias = datosmateria.objects.all().filter(horario=horario)
        except:
            materias = {}
        context = {
            'form': materia,
            'materias': materias
        }
        return render(request, template_name, context)

    def post(self, request):
        action = request.POST.get('action')
        if action == 'agregar':
            form = MateriaForm(request.POST)
            if form.is_valid():
                try:
                    guardar_materia(request)
                    return redirect('/materia/horario')
                except Exception as e:
                    print('he fallado')
                    print(e)
                    print(type(e))
                    return redirect('/materia/horario')

        elif action == 'eliminar':
            try:
                eliminar_materias(request)
                return redirect('/materia/horario')
            except Exception as e:
                print(e)
                print(type(e))
                return redirect('/materia/horario')


class Detalles(View):
    def get(self, request, pk):
        materia = datosmateria.objects.get(pk=pk)
        try:
            hora = horas.objects.all().filter(materia=materia)
        except:
            hora = 'nada'
        print(hora)
        template_name = 'materia_detail.html'
        context = {
            'materia': materia,
            'horas': hora
        }
        return render(request, template_name, context)

    def post(self, request, pk):
        action = request.POST.get('action')
        print(action)
        if action == 'editar':
            try:
                cambiar_materia(request)
                return redirect('/materia/horario')
            except Exception as e:
                print(e)
                print(type(e))
                return HttpResponseRedirect('.')
        elif action == 'editar_hora':
            try:
                cambiar_hora(request)
                return HttpResponseRedirect('.')
            except:
                return HttpResponseRedirect('.')
        elif action == 'eliminar_hora':
            try:
                eliminar_hora(request)
                return HttpResponseRedirect('.')
            except:
                return HttpResponseRedirect('.')

templates/alertas.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="jumbotron text-center">
  <div class="page-header"><h1>Tareas</h1></div>

              <!--Tabla con el horario-->
              <table class="table table-striped table-hover">
                    <h4>Tareas agregadas</h4>
                <thead>
                  <tr>
                      <th>Nombre</th>
                      <th>Materia</th>
                      <th>Descripción</th>
                      <th>Fechas de entrega</th>
                  </tr>
                </thead>

                <tbody>

                    {% for x in tarea %}
                      <tr>
                        <td>{{x.id_tarea}}</td>
                        <td>{{x.descripcion}}</td>
                        <td>{{x.materia}}</td>
                        <td>{{x.fecha_entrega}}</td>
                        <td><a href="{% url 'tarea:editar' pk=x.pk %}" class="btn btn-success btn-xs">Editar</a></td>
                        <td>
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{x.id}}">
                                <input type="hidden" name="action" value="eliminar">
                                <button class="btn btn-danger btn-xs" type="submit">Eliminar</button>
                            </form>
                        </td>
                      </tr>
                      {% endfor %}
                </tbody>
              </table>



              <form class="form-horizontal" method="post">
                <fieldset>
                    {% csrf_token %}
                    <input type="hidden" name="action" value="agregar">
                  <legend>Agregar alertas</legend>
                  <div class="form-group">
                    <label for="nombrealerta" class="col-lg-2 control-label">Nombre</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="tarea" id="nombrealerta" placeholder="Nombre de la tarea" required>
                    </div>
                  </div>
                  <input type="hidden" name="user" value="{{request.user}}">
                  <div class="form-group">
                      <label for="materia" class="col-lg-2 control-label">Materia</label>
                      <div class="col-lg-10">
                      <select id="materia" class="form-control" name="materia">
                          {% for coso in materias %}
                            <option value="{{coso.materia}}">{{coso.materia}}</option>
                          {% endfor %}
                      </select>
                      </div>
                  </div>

                  <div class="form-group">
                    <label for="textArea" name="descripcion"class="col-lg-2 control-label">Descripción</label>
                    <div class="col-lg-10">
                      <textarea class="form-control" rows="3" name="descripcion" id="textArea"></textarea>

                    </div>
                  </div>
                  <div class="form-group">
                    <label for="fechaalerta" class="col-lg-2 control-label">Fecha</label>
                    <div class="col-lg-10">
                      <input type="date" name="fecha_entrega" class="form-control" id="fechaalerta" placeholder="Fecha de la alerta" required>
                    </div>
                  </div>


                    <div class="form-group">
                      <div class="col-lg-10 col-lg-offset-2">
                        <button type="submit" class="btn btn-primary">Agregar</button>
                      </div>
                    </div>
                  </fieldset>
                </form>
</div>
{% else %}
<footer class="text-center">
  <p>Bienvenido de vuelta <a href="/usuario/login">Inicia sesión</a></p>
  <p>¿Que esperas? <a href="/usuario/registro">Registrate</a></p>
</footer>
{% endif %}

{% endblock content %}

templates/alertas_examen.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="jumbotron text-center">
  <div class="page-header"><h1>Exámenes</h1></div>

              <!--Tabla con el horario-->
              <table class="table table-striped table-hover">
                <h4>Exámenes agregados</h4>
                <thead>
                  <tr>
                      <th>Nombre</th>
                      <th>Materia</th>
                      <th>Descripción</th>
                      <th>Fechas de entrega</th>
                  </tr>
                </thead>

                <tbody>

                    {% for x in examen %}
                      <tr>
                        <td>{{x.id_examen}}</td>
                        <td>{{x.descripcion}}</td>
                        <td>{{x.materia}}</td>
                        <td>{{x.fecha_entrega}}</td>
                        <td><a href="{% url 'examen:editar' pk=x.pk %}" class="btn btn-success btn-xs">Editar</a></td>
                        <td>
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{x.id}}">
                                <input type="hidden" name="action" value="eliminar">
                                <button class="btn btn-danger btn-xs" type="submit">Eliminar</button>
                            </form>
                        </td>
                      </tr>
                      {% endfor %}
                </tbody>
              </table>



              <form class="form-horizontal" method="post">
                <fieldset>
                    {% csrf_token %}
                    <input type="hidden" name="action" value="agregar">
                  <legend>Agregar alertas</legend>
                  <div class="form-group">
                    <label for="nombrealerta" class="col-lg-2 control-label">Nombre</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="examen" id="nombrealerta" placeholder="Nombre de la alerta" required>
                    </div>
                  </div>
                  <input type="hidden" name="user" value="{{request.user}}">
                  <div class="form-group">
                      <label for="materia" class="col-lg-2 control-label">Materia</label>
                      <div class="col-lg-10">
                      <select id="materia" class="form-control" name="materia">
                          {% for coso in materias %}
                            <option value="{{coso.materia}}">{{coso.materia}}</option>
                          {% endfor %}
                      </select>
                      </div>
                  </div>

                  <div class="form-group">
                    <label for="textArea" name="descripcion"class="col-lg-2 control-label">Descripcion</label>
                    <div class="col-lg-10">
                      <textarea class="form-control" rows="3" name="descripcion" id="textArea"></textarea>

                    </div>
                  </div>
                  <div class="form-group">
                    <label for="fechaalerta" class="col-lg-2 control-label">Fecha</label>
                    <div class="col-lg-10">
                      <input type="date" name="fecha_entrega" class="form-control" id="fechaalerta" placeholder="Fecha de la alerta" required>
                    </div>
                  </div>


                    <div class="form-group">
                      <div class="col-lg-10 col-lg-offset-1">
                        <button type="submit" class="btn btn-primary">Agregar</button>
                      </div>
                    </div>
                  </fieldset>
                </form>
</div>
{% else %}
<footer class="text-center">
  <p>Bienvenido de vuelta <a href="/usuario/login">Inicia sesión</a></p>

  <p>¿Que esperas? <a href="/usuario/registro">Registrate</a></p>
</footer>
{% endif %}

{% endblock content %}

templates/base.html
<!DOCTYPE html>

<!-- define angular app -->
<html>
{% load staticfiles %}
{% load static %}
<head>
  <!-- SCROLLS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" />
  <title>Junosty</title>
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <!-- <script src="https://cdn.firebase.com/js/client/2.4.2/firebase.js"></script>
  <script src="https://www.gstatic.com/firebasejs/3.2.1/firebase.js"></script> -->
  <!-- <script>
	var config = {
        apiKey: "AIzaSyAYauqF86mGkJgNeeocAnwIrdOqvpVYyzI",
        authDomain: "ving-328c9.firebaseapp.com",
        databaseURL: "https://ving-328c9.firebaseio.com",
        storageBucket: "gs://ving-328c9.appspot.com",
      };
      var uid = '';
      firebase.initializeApp(config);
      function enviando(){
          //console.log("shimon" + jQuery('#cotiza').val())
          email = $('#email').val();
          password = $('#pass').val();
          name = $('#materiaalerta').val();
          last_name = $('#apregistro').val();
          boleta = $('#boletaregistro').val();
          console.log(email);
          console.log(password);
          console.log(name);
          console.log(last_name);
          console.log(boleta);
        // var ref = new firebase.database().ref().child('Users');
        //     ref.push({
        //       Nombre: 'holis',
        //       Boleta: '212321',
        //     });

        firebase.auth().createUserWithEmailAndPassword(email, password).catch(function(error) {
          // Handle Errors here.
          var errorCode = error.code;
          var errorMessage = error.message;
          // [START_EXCLUDE]
          if (errorCode == 'auth/weak-password') {
            alert('The password is too weak.');
          } else {
            alert(errorMessage);
          }
          else if (error == null){
              console.log('todo oc ');
          }
          console.log('todo oc mami');
          console.log(error);
          // [END_EXCLUDE]
        });
        firebase.auth().signInWithEmailAndPassword(email, password).catch(function(error, authData) {
          // Handle Errors here.
          var errorCode = error.code;
          var errorMessage = error.message;
          // [START_EXCLUDE]
          if (errorCode === 'auth/wrong-password') {
            alert('Wrong password.');
          } else {
            alert(errorMessage);
          }
          if(error == null){
              alert('no hubo ningun error');
              uid = authData.uid;
          }
          console.log(error);

          // [END_EXCLUDE]
        });
        var ref = new firebase.database().ref().child('Users').child(uid);
            ref.set({
              nombre: name,
              apellidos: last_name,
              boleta: boleta,
              contrasena: password
            });
        firebase.auth().signOut();


      }
</script> -->
  <!-- SPELLS -->
  <!-- <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.25/angular.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.25/angular-route.js"></script>
  <script src="{% static 'script.js' %}"></script> -->
</head>

<!-- define controlador de angular -->
<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand">Junosty</a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="/usuario/perfil"><i class="fa fa-user"></i> Perfil</a></li>
        <li><a href="/materia/horario"><i class="fa fa-pencil"></i> Materias</a></li>
        <li><a href="/semestre/horario"><i class="fa fa-clock-o"></i> Horario</a></li>
        <li><a href="/tarea/alertas"><i class="fa fa-bell"></i> Tareas</a></li>
        <li><a href="/examen/alertas"><i class="fa fa-bell"></i> Examenes</a></li>
        <li><a href="/usuario/logout"><i class="fa fa-user"></i> Cerrar Sesion</a></li>
        {%else%}
        <li><a href="/usuario/index"><i class = "fa fa-circle-o"></i> Inicio</a></li>
        {% endif %}

      </ul>
    </div>
  </nav>

  <div id="main" class="container">

    <!-- modelado de angular -->
		<!-- aquí es donde se inyectará el codigo -->
    <!-- <div ng-view></div> -->
    {% block content %}{% endblock content %}
  </div>

</body>

</html>

templates/examen_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<style media="screen">
    .perro_master{
        float: left;
        width: 250px;
        padding-left: 30px;
    }

</style>
    <div class="jumbotron text-center">
        <div class="page-header"><h3>Editar</h3></div>
            <form method="post" class="form-horizontal">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{examen.id}}">
                <div class="form-group">
                  <label for="nombremateria" class="col-lg-2 control-label">Nombre</label>
                  <div class="col-lg-10">
                      <input type="text" class="form-control" name="examen" value="{{examen.id_examen}}">
                  </div>
                </div>
                <div class="form-group">
                  <label for="nombremateria" class="col-lg-2 control-label">Descripcion</label>
                  <div class="col-lg-10">
                      <input type="text" class="form-control" name="descripcion" value="{{examen.descripcion}}">
                  </div>
                </div>
                <div class="form-group">
                  <label for="nombremateria" class="col-lg-2 control-label">Materia</label>
                  <div class="col-lg-10">
                      <select class="form-control" name="materia">
                          {% for coso in materias %}
                            <option value="{{coso.materia}}">{{coso.materia}}</option>
                          {% endfor %}
                      </select>
                  </div>
                </div>
                <div class="form-group">
                    <label for="nombremateria" class="col-lg-2 control-label">Fecha</label>
                    <div class="col-lg-10">
                      <input type="date" class="form-control" name="fecha_entrega" value="{{examen.fecha_entrega}}">
                  </div>
                </div>
                <input type="hidden" name="user" value="{{examen.user}}">
                <div class="form-group">
                  <div class="col-lg-10 col-lg-offset-2">
                    <button type="submit" class="btn btn-primary">Actualizar</button>
                  </div>
                </div>
            </form>
    </div>
{% endblock content %}

templates/horario.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="jumbotron text-center">
  <div class="page-header"><h1>Horario</h1></div>
              <table class="table table-striped table-hover ">
                <thead>
                  <tr>
                      <th data-field="">Grupo</th>
                      <th data-field="">Materia</th>
                      <th data-field="">Profesor</th>
                      <th data-field="">Lunes</th>
                      <th data-field="">Martes</th>
                      <th data-field="">Miercoles</th>
                      <th data-field="">Jueves</th>
                      <th data-field="">Viernes</th>
                  </tr>
                </thead>

                <tbody>
                {% for mate in materita %}


                  <tr>
                    <td>{{mate.grupo}}</td>
                    <td>{{mate.materia}}</td>
                    <td>{{mate.profesor}}</td>
                    <td>
                        {% for ho in horitas %}
                            {% if mate == ho.materia %}
                                {% if ho.fecha == 'Lunes' %}
                                    {{ho.hora}}-{{ho.fin}}
                                {% endif %}

                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for ho in horitas %}
                            {% if mate == ho.materia %}
                                {% if ho.fecha == 'Martes' %}
                                    {{ho.hora}}-{{ho.fin}}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for ho in horitas %}
                            {% if mate == ho.materia %}
                                {% if ho.fecha == 'Miercoles' %}
                                    {{ho.hora}}-{{ho.fin}}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for ho in horitas %}
                            {% if mate == ho.materia %}
                                {% if ho.fecha == 'Jueves' %}
                                    {{ho.hora}}-{{ho.fin}}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for ho in horitas %}
                            {% if mate == ho.materia %}
                                {% if ho.fecha == 'Viernes' %}
                                    {{ho.hora}}-{{ho.fin}}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </td>
                  </tr>
                  {% endfor %}

                </tbody>
              </table>

</div>
{% else %}
<footer class="text-center">
  <p>Bienvenido de vuelta <a href="/usuario/login">Inicia sesión</a></p>

  <p>¿Que esperas? <a href="/usuario/registro">Registrate</a></p>
</footer>
{% endif %}
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<footer class="text-center">

<h1>¡Bienvenido a Junosty!</h1>
<br>
<h4>¡Tu identificación, horario, tareas y exámenes en un mismo lugar!</h4>
<br><br><br>
  <p>Bienvenido de vuelta <a href="/usuario/login">Inicia sesión</a></p>

  <p>¿Que esperas? <a href="/usuario/registro">Registrate</a></p>
</footer>
{% endblock content %}

templates/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<div class="jumbotron text-center">
  <div class="page-header"><h1>Login</h1></div>
    <form class="form-horizontal" method="POST">
        {% csrf_token %}
      <fieldset>
        <legend>¡Inicia sesión!</legend>
        <div class="form-group">
          <label for="boletalogin" class="col-lg-2 control-label">Correo</label>
          <div class="col-lg-10">
            <input type="text" name="no_boleta" class="form-control" id="boletalogin" placeholder="Correo electronico" required>
          </div>
        </div>
        <div class="form-group">
          <label for="passlogin" class="col-lg-2 control-label">Contraseña</label>
          <div class="col-lg-10">
            <input type="password" name="contrasena" class="form-control" id="passlogin" placeholder="Contraseña" required>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-1">
            <button type="submit" class="btn btn-success">Iniciar sesión</button>
          </div>
        </div>
      </fieldset>
    </form>
</div>

{% endblock content %}

templates/materias.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="jumbotron text-center">
  <div class="page-header"><h1>Materia</h1></div>

              <!--Tabla con el horario-->
              <table class="table table-striped table-hover">
                <h4>Materias agregadas</h4>
                <thead>
                  <tr>
                      <th>Grupo</th>
                      <th>Materia</th>
                      <th>Profesor</th>
                  </tr>
                </thead>

                <tbody>
                    {% for holis in materias %}
                      <tr>
                        <td>{{holis.grupo}}</td>
                        <td>{{holis.materia}}</td>
                        <td>{{holis.profesor}}</td>
                        <td><a href="{% url 'materia:editar' pk=holis.pk %}" class="btn btn-success btn-xs">Editar</a></td>
                        <td>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{holis.id}}">
                                <input type="hidden" name="action" value="eliminar">
                                <button class="btn btn-danger btn-xs">Eliminar</button>
                            </form>
                        </td>
                      </tr>
                  {% endfor %}
                </tbody>
              </table>



              <form class="form-horizontal" method="POST">
                <fieldset>
                    {% csrf_token %}
                    <input type="hidden" name="action" value="agregar">
                  <legend>Agregar Materias</legend>
                  <div class="form-group">
                    <label for="grupomateria" class="col-lg-2 control-label">Grupo</label>
                    <div class="col-lg-10">
                        {{form.grupo}}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="nombremateria" class="col-lg-2 control-label">Materia</label>
                    <div class="col-lg-10">
                        {{ form.materia }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="profesormateria" class="col-lg-2 control-label">Profesor</label>
                    <div class="col-lg-10">
                        {{form.profesor}}
                    </div>
                  </div>
                    <div class="form-group">
                      <div class="col-lg-10 col-lg-offset-2">
                        <button type="reset" class="btn btn-default">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Agregar</button>
                      </div>
                    </div>
                  </fieldset>
                </form>
</div>
{% else %}
<footer class="text-center">
  <p>Bienvenido de vuelta <a href="/usuario/login">Inicia sesión</a></p>

  <p>¿Que esperas? <a href="/usuario/registro">Registrate</a></p>
</footer>
{% endif %}
{% endblock content %}

templates/perfil.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

{% if user.is_authenticated %}
<div class="jumbotron text-center">
	<div class="page-header"><h1>Perfil</h1></div>
	<div class="page-header"><h1>{{ message }}</h1></div>

	<img class="" src="{{request.user.datosusuario.qr}}">
	<p>{{request.user.datosusuario.no_boleta}}</p>
    <p>{{request.user.datosusuario.nombre}}</p>
    <a href= "/usuario/modificardatos" class="btn btn-default" ng-model="checked" aria-label="Toggle ngHide">Modificar perfil</a><br/>
</div>


<!--Modificar perfil-->

<div>

	<div class="modal">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title">Modal title</h4>
	      </div>
	      <div class="modal-body">
	        <p>One fine body…</p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <button type="button" class="btn btn-primary">Save changes</button>
	      </div>
	    </div>
	  </div>
	</div>
</div>
<div>

</div>

{% else %}
<footer class="text-center">
  <p>Bienvenido de vuelta <a href="/usuario/login">Inicia sesión</a></p>

  <p>¿Que esperas? <a href="/usuario/registro">Registrate</a></p>
</footer>
{% endif %}

{% endblock content %}